spring.application.name=usuario

aws.cognito.region=us-east-1
aws.cognito.user-pool-id=us-east-1_i9KTsLGMs
aws.cognito.app-client-id=1ivmlrra5ah4ffgjru25as6jj4

aws.access-key-id=AKIAQXNUWCPQQY6V5ROQ
aws.secret-access-key=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

server.port=${PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://bd-unilab-rds.c6pq6ogsw00v.us-east-1.rds.amazonaws.com:5432/bd_usuarios}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Postgres2026}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect